services:
  # PostgreSQL ma'lumotlar bazasi
  postgres:
    image: postgres:16-alpine
    container_name: vet_advice_bot_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: vet_advice_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vet_advice_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vet_advice_bot"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Vet Advice Bot
  vet_advice_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vet_advice_bot_app_prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database sozlamalari
      DB_HOST: postgres
      DB_NAME: vet_advice_bot
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-root}
      # Telegram bot token
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - vet_advice_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
    driver: local

networks:
  vet_advice_network:
    driver: bridge
